version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www
        container_name: php_app
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        depends_on:
            - php
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
